FROM golang:1.17 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service

WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF

COPY --from=build_sales-api /service/service /service/service
WORKDIR /service/
CMD ["./service"]

LABEL org.opencontainers.image.create="${BUILD_DATE}" \
  org.opencontainers.image.title="sales-api" \
  org.opencontainers.image.authors="Christoffer Lindowx <clindow@gmail.com>" \
  org.opencontainers.image.revision="${BUILD_REF}" \
  org.opencontainers.image.vendor="Christoffer"
